stages:
  - build
  - staging

before_script:
  - |
    # docker variables for name and tag of new image
    export DOCKER_TAG="${CI_COMMIT_SHA:0:8}"
    export DOCKER_REPO="$CI_REGISTRY_IMAGE"
    export DOCKER_IMAGE="${DOCKER_REPO}:${DOCKER_TAG}"
    export DOCKER_CACHE_IMAGE="${DOCKER_REPO}:${CI_COMMIT_REF_NAME}"

# Build of docker image and push it to project Container registry
build:
  # Lightweight image with support of running docker in docker
  image: docker:stable
  services:
    - docker:dind
  stage: build
  script:
    # Login to Container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    # Load existing images for build optimisation
    - docker pull "$DOCKER_CACHE_IMAGE" || docker pull "${DOCKER_REPO}:deploy" || true # allow failure
    - docker pull "$DOCKER_IMAGE" || true # allow failure
    # Build our docker image
    - docker build --pull --cache-from "$DOCKER_IMAGE" --cache-from "$DOCKER_CACHE_IMAGE" --cache-from "${DOCKER_REPO}:deploy" -t "$DOCKER_IMAGE" .
    # Save built image to Container registry under branch name tag and commit hash tag
    - docker push "$DOCKER_IMAGE"
    - docker tag "$DOCKER_IMAGE" "$DOCKER_CACHE_IMAGE"
    - docker push "$DOCKER_CACHE_IMAGE"
  only:
    - deploy

staging:
  # Lightweight image with ssh
  image: kroniak/ssh-client
  stage: staging
  script:
    - ls -la
    # Set right chmod on SSH key file
    - chmod 400 $DEPLOY_SSH_KEY
    # Login to Gitlab Container registry
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_SSH_KEY "${DEPLOY_SSH_USER}@${DEPLOY_HOST}" "sudo docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}"
    # Remove old containers and images if exists
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_SSH_KEY "${DEPLOY_SSH_USER}@${DEPLOY_HOST}" "sudo docker rm -f ${CI_PROJECT_NAME} || true"
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_SSH_KEY "${DEPLOY_SSH_USER}@${DEPLOY_HOST}" "sudo docker rmi \$(sudo docker images -q ${DOCKER_REPO}) || true"
    # Download and run new image
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_TEST "${MASTER_SSH_USER}@${MASTER_HOST}"
      sudo docker run
      --name=$CI_PROJECT_NAME
      --restart=always
      --network="host"
      -p 5001:5001
      -v "/app/storage:/src/storage"
      -d $DOCKER_IMAGE
  only:
    - deploy
